version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: sladen/node:10.15.0-stretch-jdk8
    steps:
      - checkout
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
      - run:
          name: install dependencies
          command: npm start & wait-on http://localhost:3000

      - run:
          name: run tests
          command: cypress run

    