version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: "CI=false npm run build && npm install" # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          start: "npm start" # start server before running tests
          record: true # record results on Cypress Dashboard
          group: "all tests" # name this group "all tests" on the dashboard
          wait-on: "http-get://127.0.0.1:3000"
